### ISSUE TITLE
Improve projectile physics

### ISSUE THREAD

**Issue by sashadgt** [NestorTejero/ES2016B#284]
## Tasks to do:
- Create prefab for each type of projectile (with correspondent model).
- Assign each projectile to the tower/unit that has to shoot it.
- Make sure that each level of the UB building/tower has a different type of projectile (Level 1: rock, Level 2: bullet, Level 3: laser).
- Projectile speed has to increase at each level (to be done correctly in issue #292).
- When attacking, the projectile won't always hit the target (maybe it will hit another enemy or a building standing in the way) . If it hits an enemy, its health should be decreased.

**Comment by kkaren** [comment]
## Definition of done:
**Prefabs**
- There is a **prefab for each type of projectile** (rock, bullet, laser, Iphone, calculator, barrel, banner, exam, broom).
- Each prefab has the right **model** in it (except bullet and laser because they are not created yet).
- There is a projectile prefab (**rock**) assigned to the towers initially.
- There is a projectile prefab assigned to each type of **unit**:
  - **Iphone->** Angry student
  - **Calculator ->** Freshman student
  - **Barrel ->** Exchange student
  - **Banner ->** Manifestant
  - **Exam ->** Professor
  - **Broom ->** Janitor
- All prefabs have **colliders** placed correctly for the impact.

**Code**
- When a weapon shoots a projectile and this **collides with a target** (enemy), its **health decreases**.
- When a weapon shoots a projectile and this **hits against a building** standing in the way, there is **no damage done** to any enemy.
- Each **level of the tower** shoots a different type of projectile:
  - **Rock** -> level 1
  - **Bullet** -> level 2
  - **Laser** -> level 3
   **NOTE: there are no models for bullet and laser yet**
- At each of these levels, the projectile **speed** is different (it **increases**).

Estimated time: 6h

**Comment by kkaren** [comment]
Real time: 12h
