### ISSUE TITLE
Merge Design and content from web

### ISSUE THREAD

**Issue by pauortega** [NestorTejero/ES2016B#383]
DOD:
* Website is filled up.

**Comment by stefanlonn** [comment]
Commits done (instead of PR)

2dfd5ae079c130c33299836dae7dfd9f1a34af2d
760db33344392a6355bc882360fd1b5cb61f74e5
175c2492a32ffd4f72349ee5d2aea73567f58915
fdd30f8f81fa5f5dfdc287f7e3fae0cced40f7eb
85485181337232bf9524853ffcdd54524b787d05
7558cc0b5742ad123d6fb461e2dad3529c0055dd
50c80209dd3308e0e6f076082f5947eb08b2fb06
80d9283b5036e0da86a120fc8a2e39da7d6fdd30
2d403b6befab230c7487b96ba015779cbd671dea
